language: java
script:  ant build
deploy:
       provider: s3
       access_key_id: $Vijay_key
       secret_access_key: $vijay_pwd
       bucket: "S3 vijayhegdebucket2"
       skip-cleanup: true
