language: java
jdk:
	-oraclejdk11
script: ant build
deploy:
     - provider: s3
       access_key_id: $Vijay_id
       secret_access_key: $vijay_key
       bucket: 'vijayhegdebucket2'
       region: 'us-east-1'
       skip-cleanup: true
